// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package ru.spbau.mit;

public final class Protocol {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_protocol_Array_descriptor;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_protocol_ServerCommand_descriptor;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_protocol_ServerResponse_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_protocol_Array_fieldAccessorTable;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_protocol_ServerCommand_fieldAccessorTable;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_protocol_ServerResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\016protocol.proto\022\010protocol\"\032\n\005Array\022\021\n\005v" +
                        "alue\030\001 \003(\005B\002\020\001\"1\n\rServerCommand\022\014\n\004type\030" +
                        "\001 \002(\t\022\022\n\nserverType\030\002 \001(\t\"`\n\016ServerRespo" +
                        "nse\022\016\n\006result\030\001 \002(\t\022\014\n\004port\030\002 \001(\005\022\026\n\016mea" +
                        "nHandleTime\030\003 \001(\001\022\030\n\020meanResponseTime\030\004 " +
                        "\001(\001B\030\n\014ru.spbau.mitB\010Protocol"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_protocol_Array_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_protocol_Array_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_protocol_Array_descriptor,
                new java.lang.String[]{"Value",});
        internal_static_protocol_ServerCommand_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_protocol_ServerCommand_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_protocol_ServerCommand_descriptor,
                new java.lang.String[]{"Type", "ServerType",});
        internal_static_protocol_ServerResponse_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_protocol_ServerResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_protocol_ServerResponse_descriptor,
                new java.lang.String[]{"Result", "Port", "MeanHandleTime", "MeanResponseTime",});
    }

    private Protocol() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    public interface ArrayOrBuilder extends
            // @@protoc_insertion_point(interface_extends:protocol.Array)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated int32 value = 1 [packed = true];</code>
         */
        java.util.List<java.lang.Integer> getValueList();

        /**
         * <code>repeated int32 value = 1 [packed = true];</code>
         */
        int getValueCount();

        /**
         * <code>repeated int32 value = 1 [packed = true];</code>
         */
        int getValue(int index);
    }
    public interface ServerCommandOrBuilder extends
            // @@protoc_insertion_point(interface_extends:protocol.ServerCommand)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string type = 1;</code>
         */
        boolean hasType();

        /**
         * <code>required string type = 1;</code>
         */
        java.lang.String getType();

        /**
         * <code>required string type = 1;</code>
         */
        com.google.protobuf.ByteString
        getTypeBytes();

        /**
         * <code>optional string serverType = 2;</code>
         */
        boolean hasServerType();

        /**
         * <code>optional string serverType = 2;</code>
         */
        java.lang.String getServerType();

        /**
         * <code>optional string serverType = 2;</code>
         */
        com.google.protobuf.ByteString
        getServerTypeBytes();
    }
    public interface ServerResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:protocol.ServerResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string result = 1;</code>
         */
        boolean hasResult();

        /**
         * <code>required string result = 1;</code>
         */
        java.lang.String getResult();

        /**
         * <code>required string result = 1;</code>
         */
        com.google.protobuf.ByteString
        getResultBytes();

        /**
         * <code>optional int32 port = 2;</code>
         */
        boolean hasPort();

        /**
         * <code>optional int32 port = 2;</code>
         */
        int getPort();

        /**
         * <code>optional double meanHandleTime = 3;</code>
         */
        boolean hasMeanHandleTime();

        /**
         * <code>optional double meanHandleTime = 3;</code>
         */
        double getMeanHandleTime();

        /**
         * <code>optional double meanResponseTime = 4;</code>
         */
        boolean hasMeanResponseTime();

        /**
         * <code>optional double meanResponseTime = 4;</code>
         */
        double getMeanResponseTime();
    }

    /**
     * Protobuf type {@code protocol.Array}
     */
    public static final class Array extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:protocol.Array)
            ArrayOrBuilder {
        public static final int VALUE_FIELD_NUMBER = 1;
        private static final Array defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<Array> PARSER =
                new com.google.protobuf.AbstractParser<Array>() {
                    public Array parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new Array(input, extensionRegistry);
                    }
                };

        static {
            defaultInstance = new Array(true);
            defaultInstance.initFields();
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private java.util.List<java.lang.Integer> value_;
        private int valueMemoizedSerializedSize = -1;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Array.newBuilder() to construct.
        private Array(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Array(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Array(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                value_ = new java.util.ArrayList<java.lang.Integer>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            value_.add(input.readInt32());
                            break;
                        }
                        case 10: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                                value_ = new java.util.ArrayList<java.lang.Integer>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                value_.add(input.readInt32());
                            }
                            input.popLimit(limit);
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    value_ = java.util.Collections.unmodifiableList(value_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static Array getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ru.spbau.mit.Protocol.internal_static_protocol_Array_descriptor;
        }

        public static ru.spbau.mit.Protocol.Array parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ru.spbau.mit.Protocol.Array parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ru.spbau.mit.Protocol.Array parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ru.spbau.mit.Protocol.Array parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ru.spbau.mit.Protocol.Array parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ru.spbau.mit.Protocol.Array parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static ru.spbau.mit.Protocol.Array parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static ru.spbau.mit.Protocol.Array parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static ru.spbau.mit.Protocol.Array parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ru.spbau.mit.Protocol.Array parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(ru.spbau.mit.Protocol.Array prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Array getDefaultInstanceForType() {
            return defaultInstance;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ru.spbau.mit.Protocol.internal_static_protocol_Array_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ru.spbau.mit.Protocol.Array.class, ru.spbau.mit.Protocol.Array.Builder.class);
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Array> getParserForType() {
            return PARSER;
        }

        /**
         * <code>repeated int32 value = 1 [packed = true];</code>
         */
        public java.util.List<java.lang.Integer>
        getValueList() {
            return value_;
        }

        /**
         * <code>repeated int32 value = 1 [packed = true];</code>
         */
        public int getValueCount() {
            return value_.size();
        }

        /**
         * <code>repeated int32 value = 1 [packed = true];</code>
         */
        public int getValue(int index) {
            return value_.get(index);
        }

        private void initFields() {
            value_ = java.util.Collections.emptyList();
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (getValueList().size() > 0) {
                output.writeRawVarint32(10);
                output.writeRawVarint32(valueMemoizedSerializedSize);
            }
            for (int i = 0; i < value_.size(); i++) {
                output.writeInt32NoTag(value_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            {
                int dataSize = 0;
                for (int i = 0; i < value_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(value_.get(i));
                }
                size += dataSize;
                if (!getValueList().isEmpty()) {
                    size += 1;
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(dataSize);
                }
                valueMemoizedSerializedSize = dataSize;
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code protocol.Array}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:protocol.Array)
                ru.spbau.mit.Protocol.ArrayOrBuilder {
            private int bitField0_;
            private java.util.List<java.lang.Integer> value_ = java.util.Collections.emptyList();

            // Construct using ru.spbau.mit.Protocol.Array.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ru.spbau.mit.Protocol.internal_static_protocol_Array_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ru.spbau.mit.Protocol.internal_static_protocol_Array_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ru.spbau.mit.Protocol.Array.class, ru.spbau.mit.Protocol.Array.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                value_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ru.spbau.mit.Protocol.internal_static_protocol_Array_descriptor;
            }

            public ru.spbau.mit.Protocol.Array getDefaultInstanceForType() {
                return ru.spbau.mit.Protocol.Array.getDefaultInstance();
            }

            public ru.spbau.mit.Protocol.Array build() {
                ru.spbau.mit.Protocol.Array result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public ru.spbau.mit.Protocol.Array buildPartial() {
                ru.spbau.mit.Protocol.Array result = new ru.spbau.mit.Protocol.Array(this);
                int from_bitField0_ = bitField0_;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    value_ = java.util.Collections.unmodifiableList(value_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.value_ = value_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ru.spbau.mit.Protocol.Array) {
                    return mergeFrom((ru.spbau.mit.Protocol.Array) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ru.spbau.mit.Protocol.Array other) {
                if (other == ru.spbau.mit.Protocol.Array.getDefaultInstance()) return this;
                if (!other.value_.isEmpty()) {
                    if (value_.isEmpty()) {
                        value_ = other.value_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureValueIsMutable();
                        value_.addAll(other.value_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ru.spbau.mit.Protocol.Array parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ru.spbau.mit.Protocol.Array) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private void ensureValueIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    value_ = new java.util.ArrayList<java.lang.Integer>(value_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated int32 value = 1 [packed = true];</code>
             */
            public java.util.List<java.lang.Integer>
            getValueList() {
                return java.util.Collections.unmodifiableList(value_);
            }

            /**
             * <code>repeated int32 value = 1 [packed = true];</code>
             */
            public int getValueCount() {
                return value_.size();
            }

            /**
             * <code>repeated int32 value = 1 [packed = true];</code>
             */
            public int getValue(int index) {
                return value_.get(index);
            }

            /**
             * <code>repeated int32 value = 1 [packed = true];</code>
             */
            public Builder setValue(
                    int index, int value) {
                ensureValueIsMutable();
                value_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int32 value = 1 [packed = true];</code>
             */
            public Builder addValue(int value) {
                ensureValueIsMutable();
                value_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int32 value = 1 [packed = true];</code>
             */
            public Builder addAllValue(
                    java.lang.Iterable<? extends java.lang.Integer> values) {
                ensureValueIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, value_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int32 value = 1 [packed = true];</code>
             */
            public Builder clearValue() {
                value_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:protocol.Array)
        }

        // @@protoc_insertion_point(class_scope:protocol.Array)
    }

    /**
     * Protobuf type {@code protocol.ServerCommand}
     */
    public static final class ServerCommand extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:protocol.ServerCommand)
            ServerCommandOrBuilder {
        public static final int TYPE_FIELD_NUMBER = 1;
        public static final int SERVERTYPE_FIELD_NUMBER = 2;
        private static final ServerCommand defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<ServerCommand> PARSER =
                new com.google.protobuf.AbstractParser<ServerCommand>() {
                    public ServerCommand parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new ServerCommand(input, extensionRegistry);
                    }
                };

        static {
            defaultInstance = new ServerCommand(true);
            defaultInstance.initFields();
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private java.lang.Object type_;
        private java.lang.Object serverType_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use ServerCommand.newBuilder() to construct.
        private ServerCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private ServerCommand(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private ServerCommand(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            type_ = bs;
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            serverType_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static ServerCommand getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ru.spbau.mit.Protocol.internal_static_protocol_ServerCommand_descriptor;
        }

        public static ru.spbau.mit.Protocol.ServerCommand parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ru.spbau.mit.Protocol.ServerCommand parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ru.spbau.mit.Protocol.ServerCommand parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ru.spbau.mit.Protocol.ServerCommand parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ru.spbau.mit.Protocol.ServerCommand parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ru.spbau.mit.Protocol.ServerCommand parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static ru.spbau.mit.Protocol.ServerCommand parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static ru.spbau.mit.Protocol.ServerCommand parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static ru.spbau.mit.Protocol.ServerCommand parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ru.spbau.mit.Protocol.ServerCommand parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(ru.spbau.mit.Protocol.ServerCommand prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public ServerCommand getDefaultInstanceForType() {
            return defaultInstance;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ru.spbau.mit.Protocol.internal_static_protocol_ServerCommand_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ru.spbau.mit.Protocol.ServerCommand.class, ru.spbau.mit.Protocol.ServerCommand.Builder.class);
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ServerCommand> getParserForType() {
            return PARSER;
        }

        /**
         * <code>required string type = 1;</code>
         */
        public boolean hasType() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string type = 1;</code>
         */
        public java.lang.String getType() {
            java.lang.Object ref = type_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    type_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string type = 1;</code>
         */
        public com.google.protobuf.ByteString
        getTypeBytes() {
            java.lang.Object ref = type_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                type_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string serverType = 2;</code>
         */
        public boolean hasServerType() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional string serverType = 2;</code>
         */
        public java.lang.String getServerType() {
            java.lang.Object ref = serverType_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    serverType_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string serverType = 2;</code>
         */
        public com.google.protobuf.ByteString
        getServerTypeBytes() {
            java.lang.Object ref = serverType_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                serverType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            type_ = "";
            serverType_ = "";
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getTypeBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getServerTypeBytes());
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getTypeBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getServerTypeBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code protocol.ServerCommand}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:protocol.ServerCommand)
                ru.spbau.mit.Protocol.ServerCommandOrBuilder {
            private int bitField0_;
            private java.lang.Object type_ = "";
            private java.lang.Object serverType_ = "";

            // Construct using ru.spbau.mit.Protocol.ServerCommand.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ru.spbau.mit.Protocol.internal_static_protocol_ServerCommand_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ru.spbau.mit.Protocol.internal_static_protocol_ServerCommand_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ru.spbau.mit.Protocol.ServerCommand.class, ru.spbau.mit.Protocol.ServerCommand.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                type_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                serverType_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ru.spbau.mit.Protocol.internal_static_protocol_ServerCommand_descriptor;
            }

            public ru.spbau.mit.Protocol.ServerCommand getDefaultInstanceForType() {
                return ru.spbau.mit.Protocol.ServerCommand.getDefaultInstance();
            }

            public ru.spbau.mit.Protocol.ServerCommand build() {
                ru.spbau.mit.Protocol.ServerCommand result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public ru.spbau.mit.Protocol.ServerCommand buildPartial() {
                ru.spbau.mit.Protocol.ServerCommand result = new ru.spbau.mit.Protocol.ServerCommand(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.type_ = type_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.serverType_ = serverType_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ru.spbau.mit.Protocol.ServerCommand) {
                    return mergeFrom((ru.spbau.mit.Protocol.ServerCommand) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ru.spbau.mit.Protocol.ServerCommand other) {
                if (other == ru.spbau.mit.Protocol.ServerCommand.getDefaultInstance()) return this;
                if (other.hasType()) {
                    bitField0_ |= 0x00000001;
                    type_ = other.type_;
                    onChanged();
                }
                if (other.hasServerType()) {
                    bitField0_ |= 0x00000002;
                    serverType_ = other.serverType_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasType()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ru.spbau.mit.Protocol.ServerCommand parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ru.spbau.mit.Protocol.ServerCommand) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required string type = 1;</code>
             */
            public boolean hasType() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string type = 1;</code>
             */
            public java.lang.String getType() {
                java.lang.Object ref = type_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        type_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string type = 1;</code>
             */
            public Builder setType(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string type = 1;</code>
             */
            public com.google.protobuf.ByteString
            getTypeBytes() {
                java.lang.Object ref = type_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    type_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string type = 1;</code>
             */
            public Builder setTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string type = 1;</code>
             */
            public Builder clearType() {
                bitField0_ = (bitField0_ & ~0x00000001);
                type_ = getDefaultInstance().getType();
                onChanged();
                return this;
            }

            /**
             * <code>optional string serverType = 2;</code>
             */
            public boolean hasServerType() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional string serverType = 2;</code>
             */
            public java.lang.String getServerType() {
                java.lang.Object ref = serverType_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        serverType_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string serverType = 2;</code>
             */
            public Builder setServerType(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                serverType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string serverType = 2;</code>
             */
            public com.google.protobuf.ByteString
            getServerTypeBytes() {
                java.lang.Object ref = serverType_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    serverType_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string serverType = 2;</code>
             */
            public Builder setServerTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                serverType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string serverType = 2;</code>
             */
            public Builder clearServerType() {
                bitField0_ = (bitField0_ & ~0x00000002);
                serverType_ = getDefaultInstance().getServerType();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:protocol.ServerCommand)
        }

        // @@protoc_insertion_point(class_scope:protocol.ServerCommand)
    }

    /**
     * Protobuf type {@code protocol.ServerResponse}
     */
    public static final class ServerResponse extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:protocol.ServerResponse)
            ServerResponseOrBuilder {
        public static final int RESULT_FIELD_NUMBER = 1;
        public static final int PORT_FIELD_NUMBER = 2;
        public static final int MEANHANDLETIME_FIELD_NUMBER = 3;
        public static final int MEANRESPONSETIME_FIELD_NUMBER = 4;
        private static final ServerResponse defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<ServerResponse> PARSER =
                new com.google.protobuf.AbstractParser<ServerResponse>() {
                    public ServerResponse parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new ServerResponse(input, extensionRegistry);
                    }
                };

        static {
            defaultInstance = new ServerResponse(true);
            defaultInstance.initFields();
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private java.lang.Object result_;
        private int port_;
        private double meanHandleTime_;
        private double meanResponseTime_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use ServerResponse.newBuilder() to construct.
        private ServerResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private ServerResponse(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private ServerResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            result_ = bs;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            port_ = input.readInt32();
                            break;
                        }
                        case 25: {
                            bitField0_ |= 0x00000004;
                            meanHandleTime_ = input.readDouble();
                            break;
                        }
                        case 33: {
                            bitField0_ |= 0x00000008;
                            meanResponseTime_ = input.readDouble();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static ServerResponse getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ru.spbau.mit.Protocol.internal_static_protocol_ServerResponse_descriptor;
        }

        public static ru.spbau.mit.Protocol.ServerResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ru.spbau.mit.Protocol.ServerResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ru.spbau.mit.Protocol.ServerResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ru.spbau.mit.Protocol.ServerResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ru.spbau.mit.Protocol.ServerResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ru.spbau.mit.Protocol.ServerResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static ru.spbau.mit.Protocol.ServerResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static ru.spbau.mit.Protocol.ServerResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static ru.spbau.mit.Protocol.ServerResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ru.spbau.mit.Protocol.ServerResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(ru.spbau.mit.Protocol.ServerResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public ServerResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ru.spbau.mit.Protocol.internal_static_protocol_ServerResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ru.spbau.mit.Protocol.ServerResponse.class, ru.spbau.mit.Protocol.ServerResponse.Builder.class);
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ServerResponse> getParserForType() {
            return PARSER;
        }

        /**
         * <code>required string result = 1;</code>
         */
        public boolean hasResult() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string result = 1;</code>
         */
        public java.lang.String getResult() {
            java.lang.Object ref = result_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    result_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string result = 1;</code>
         */
        public com.google.protobuf.ByteString
        getResultBytes() {
            java.lang.Object ref = result_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                result_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional int32 port = 2;</code>
         */
        public boolean hasPort() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional int32 port = 2;</code>
         */
        public int getPort() {
            return port_;
        }

        /**
         * <code>optional double meanHandleTime = 3;</code>
         */
        public boolean hasMeanHandleTime() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional double meanHandleTime = 3;</code>
         */
        public double getMeanHandleTime() {
            return meanHandleTime_;
        }

        /**
         * <code>optional double meanResponseTime = 4;</code>
         */
        public boolean hasMeanResponseTime() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>optional double meanResponseTime = 4;</code>
         */
        public double getMeanResponseTime() {
            return meanResponseTime_;
        }

        private void initFields() {
            result_ = "";
            port_ = 0;
            meanHandleTime_ = 0D;
            meanResponseTime_ = 0D;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasResult()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getResultBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, port_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeDouble(3, meanHandleTime_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeDouble(4, meanResponseTime_);
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getResultBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, port_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(3, meanHandleTime_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(4, meanResponseTime_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code protocol.ServerResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:protocol.ServerResponse)
                ru.spbau.mit.Protocol.ServerResponseOrBuilder {
            private int bitField0_;
            private java.lang.Object result_ = "";
            private int port_;
            private double meanHandleTime_;
            private double meanResponseTime_;

            // Construct using ru.spbau.mit.Protocol.ServerResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ru.spbau.mit.Protocol.internal_static_protocol_ServerResponse_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ru.spbau.mit.Protocol.internal_static_protocol_ServerResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ru.spbau.mit.Protocol.ServerResponse.class, ru.spbau.mit.Protocol.ServerResponse.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                result_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                port_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                meanHandleTime_ = 0D;
                bitField0_ = (bitField0_ & ~0x00000004);
                meanResponseTime_ = 0D;
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ru.spbau.mit.Protocol.internal_static_protocol_ServerResponse_descriptor;
            }

            public ru.spbau.mit.Protocol.ServerResponse getDefaultInstanceForType() {
                return ru.spbau.mit.Protocol.ServerResponse.getDefaultInstance();
            }

            public ru.spbau.mit.Protocol.ServerResponse build() {
                ru.spbau.mit.Protocol.ServerResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public ru.spbau.mit.Protocol.ServerResponse buildPartial() {
                ru.spbau.mit.Protocol.ServerResponse result = new ru.spbau.mit.Protocol.ServerResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.result_ = result_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.port_ = port_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.meanHandleTime_ = meanHandleTime_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.meanResponseTime_ = meanResponseTime_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ru.spbau.mit.Protocol.ServerResponse) {
                    return mergeFrom((ru.spbau.mit.Protocol.ServerResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ru.spbau.mit.Protocol.ServerResponse other) {
                if (other == ru.spbau.mit.Protocol.ServerResponse.getDefaultInstance()) return this;
                if (other.hasResult()) {
                    bitField0_ |= 0x00000001;
                    result_ = other.result_;
                    onChanged();
                }
                if (other.hasPort()) {
                    setPort(other.getPort());
                }
                if (other.hasMeanHandleTime()) {
                    setMeanHandleTime(other.getMeanHandleTime());
                }
                if (other.hasMeanResponseTime()) {
                    setMeanResponseTime(other.getMeanResponseTime());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasResult()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ru.spbau.mit.Protocol.ServerResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ru.spbau.mit.Protocol.ServerResponse) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required string result = 1;</code>
             */
            public boolean hasResult() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string result = 1;</code>
             */
            public java.lang.String getResult() {
                java.lang.Object ref = result_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        result_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string result = 1;</code>
             */
            public Builder setResult(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                result_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string result = 1;</code>
             */
            public com.google.protobuf.ByteString
            getResultBytes() {
                java.lang.Object ref = result_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    result_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string result = 1;</code>
             */
            public Builder setResultBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                result_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string result = 1;</code>
             */
            public Builder clearResult() {
                bitField0_ = (bitField0_ & ~0x00000001);
                result_ = getDefaultInstance().getResult();
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 port = 2;</code>
             */
            public boolean hasPort() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional int32 port = 2;</code>
             */
            public int getPort() {
                return port_;
            }

            /**
             * <code>optional int32 port = 2;</code>
             */
            public Builder setPort(int value) {
                bitField0_ |= 0x00000002;
                port_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 port = 2;</code>
             */
            public Builder clearPort() {
                bitField0_ = (bitField0_ & ~0x00000002);
                port_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional double meanHandleTime = 3;</code>
             */
            public boolean hasMeanHandleTime() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional double meanHandleTime = 3;</code>
             */
            public double getMeanHandleTime() {
                return meanHandleTime_;
            }

            /**
             * <code>optional double meanHandleTime = 3;</code>
             */
            public Builder setMeanHandleTime(double value) {
                bitField0_ |= 0x00000004;
                meanHandleTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional double meanHandleTime = 3;</code>
             */
            public Builder clearMeanHandleTime() {
                bitField0_ = (bitField0_ & ~0x00000004);
                meanHandleTime_ = 0D;
                onChanged();
                return this;
            }

            /**
             * <code>optional double meanResponseTime = 4;</code>
             */
            public boolean hasMeanResponseTime() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>optional double meanResponseTime = 4;</code>
             */
            public double getMeanResponseTime() {
                return meanResponseTime_;
            }

            /**
             * <code>optional double meanResponseTime = 4;</code>
             */
            public Builder setMeanResponseTime(double value) {
                bitField0_ |= 0x00000008;
                meanResponseTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional double meanResponseTime = 4;</code>
             */
            public Builder clearMeanResponseTime() {
                bitField0_ = (bitField0_ & ~0x00000008);
                meanResponseTime_ = 0D;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:protocol.ServerResponse)
        }

        // @@protoc_insertion_point(class_scope:protocol.ServerResponse)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
